name: Bug report
description: File a bug report
title: "[BUG] "
labels: ["bug"]
body:
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: v1.3.2b
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Tell us what you expected to happen and what actually happened.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      placeholder: 1) ... 2) ... 3) ...
  - type: textarea
    id: logs
    attributes:
      label: Logs / Console
      render: shell
